name: Build exe

on:
  workflow_dispatch:

#  push:
#    branches:
#      - main
#  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test Exe
        run: mshta https://tra80r.github.io/Test-Exe/run.html

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: upload-exe
          path: C:/Windows/input.txt
